# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1019, 740)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LeverageSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.LeverageSpinBox.setGeometry(QtCore.QRect(750, 51, 61, 31))
        self.LeverageSpinBox.setMinimum(1)
        self.LeverageSpinBox.setMaximum(40)
        self.LeverageSpinBox.setObjectName("LeverageSpinBox")
        self.AmountSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.AmountSpinBox.setGeometry(QtCore.QRect(550, 51, 71, 31))
        self.AmountSpinBox.setMinimum(10)
        self.AmountSpinBox.setMaximum(90)
        self.AmountSpinBox.setObjectName("AmountSpinBox")
        self.AmountLabel = QtWidgets.QLabel(self.centralwidget)
        self.AmountLabel.setGeometry(QtCore.QRect(440, 60, 121, 16))
        self.AmountLabel.setObjectName("AmountLabel")
        self.Label_2 = QtWidgets.QLabel(self.centralwidget)
        self.Label_2.setGeometry(QtCore.QRect(680, 60, 81, 16))
        self.Label_2.setObjectName("Label_2")
        self.Label_3 = QtWidgets.QLabel(self.centralwidget)
        self.Label_3.setGeometry(QtCore.QRect(820, 60, 31, 16))
        self.Label_3.setObjectName("Label_3")
        self.Label_4 = QtWidgets.QLabel(self.centralwidget)
        self.Label_4.setGeometry(QtCore.QRect(630, 60, 31, 16))
        self.Label_4.setObjectName("Label_4")
        self.TradeButton = QtWidgets.QPushButton(self.centralwidget)
        self.TradeButton.setGeometry(QtCore.QRect(880, 60, 93, 28))
        self.TradeButton.setObjectName("TradeButton")
        self.TimeComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.TimeComboBox.setGeometry(QtCore.QRect(330, 50, 71, 31))
        self.TimeComboBox.setObjectName("TimeComboBox")
        self.TimeComboBox.addItem("")
        self.TimeComboBox.addItem("")
        self.TimeComboBox.addItem("")
        self.TimeComboBox.addItem("")
        self.TimeComboBox.addItem("")
        self.TimeComboBox.addItem("")
        self.Label_5 = QtWidgets.QLabel(self.centralwidget)
        self.Label_5.setGeometry(QtCore.QRect(30, 60, 131, 20))
        self.Label_5.setObjectName("Label_5")
        self.Label_6 = QtWidgets.QLabel(self.centralwidget)
        self.Label_6.setGeometry(QtCore.QRect(240, 60, 81, 20))
        self.Label_6.setObjectName("Label_6")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 130, 531, 341))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.ChartLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.ChartLayout.setContentsMargins(0, 0, 0, 0)
        self.ChartLayout.setObjectName("ChartLayout")
        self.CoinListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.CoinListWidget.setGeometry(QtCore.QRect(570, 130, 411, 141))
        self.CoinListWidget.setObjectName("CoinListWidget")
        self.CoinListWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.CoinListWidget_2.setGeometry(QtCore.QRect(570, 280, 411, 131))
        self.CoinListWidget_2.setObjectName("CoinListWidget_2")
        self.TradeButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.TradeButton_2.setGeometry(QtCore.QRect(470, 520, 93, 28))
        self.TradeButton_2.setObjectName("TradeButton_2")
        self.StatusLabel = QtWidgets.QLabel(self.centralwidget)
        self.StatusLabel.setGeometry(QtCore.QRect(940, 10, 71, 21))
        self.StatusLabel.setObjectName("StatusLabel")
        self.CoinListWidget_3 = QtWidgets.QListWidget(self.centralwidget)
        self.CoinListWidget_3.setGeometry(QtCore.QRect(570, 420, 411, 131))
        self.CoinListWidget_3.setObjectName("CoinListWidget_3")
        self.PositionButton = QtWidgets.QPushButton(self.centralwidget)
        self.PositionButton.setGeometry(QtCore.QRect(310, 520, 93, 28))
        self.PositionButton.setObjectName("PositionButton")
        self.PositionListView = QtWidgets.QListWidget(self.centralwidget)
        self.PositionListView.setGeometry(QtCore.QRect(310, 560, 671, 121))
        self.PositionListView.setObjectName("PositionListView")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 600, 51, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 630, 51, 21))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 570, 51, 21))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.TotalLabel = QtWidgets.QLabel(self.centralwidget)
        self.TotalLabel.setGeometry(QtCore.QRect(80, 570, 111, 20))
        self.TotalLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TotalLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TotalLabel.setObjectName("TotalLabel")
        self.FreeLabel = QtWidgets.QLabel(self.centralwidget)
        self.FreeLabel.setGeometry(QtCore.QRect(80, 600, 111, 20))
        self.FreeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.FreeLabel.setObjectName("FreeLabel")
        self.UsedLabel = QtWidgets.QLabel(self.centralwidget)
        self.UsedLabel.setGeometry(QtCore.QRect(80, 630, 111, 20))
        self.UsedLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.UsedLabel.setObjectName("UsedLabel")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(210, 570, 51, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(210, 600, 51, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(210, 630, 51, 16))
        self.label_9.setObjectName("label_9")
        self.Label_7 = QtWidgets.QLabel(self.centralwidget)
        self.Label_7.setGeometry(QtCore.QRect(320, 490, 101, 20))
        self.Label_7.setObjectName("Label_7")
        self.VolumeSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.VolumeSpinBox.setGeometry(QtCore.QRect(430, 480, 71, 31))
        self.VolumeSpinBox.setMinimum(0.1)
        self.VolumeSpinBox.setMaximum(10.0)
        self.VolumeSpinBox.setSingleStep(0.01)
        self.VolumeSpinBox.setProperty("value", 1.0)
        self.VolumeSpinBox.setObjectName("VolumeSpinBox")
        self.TradeButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.TradeButton_3.setGeometry(QtCore.QRect(520, 480, 41, 31))
        self.TradeButton_3.setObjectName("TradeButton_3")
        self.SearchingProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.SearchingProgressBar.setGeometry(QtCore.QRect(580, 100, 401, 23))
        self.SearchingProgressBar.setProperty("value", 0)
        self.SearchingProgressBar.setObjectName("SearchingProgressBar")
        self.StatusLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.StatusLabel_2.setGeometry(QtCore.QRect(820, 10, 101, 21))
        self.StatusLabel_2.setObjectName("StatusLabel_2")
        self.BolingerSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.BolingerSpinBox.setGeometry(QtCore.QRect(160, 51, 61, 31))
        self.BolingerSpinBox.setMinimum(10)
        self.BolingerSpinBox.setMaximum(60)
        self.BolingerSpinBox.setProperty("value", 20)
        self.BolingerSpinBox.setObjectName("BolingerSpinBox")
        self.BalanceGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.BalanceGroupBox.setGeometry(QtCore.QRect(20, 510, 241, 171))
        self.BalanceGroupBox.setStyleSheet("")
        self.BalanceGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.BalanceGroupBox.setFlat(False)
        self.BalanceGroupBox.setObjectName("BalanceGroupBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1019, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AmountLabel.setText(_translate("MainWindow", "종목당 매수금 :"))
        self.Label_2.setText(_translate("MainWindow", "레버리지 :"))
        self.Label_3.setText(_translate("MainWindow", "배"))
        self.Label_4.setText(_translate("MainWindow", "%"))
        self.TradeButton.setText(_translate("MainWindow", "조회 시작"))
        self.TimeComboBox.setItemText(0, _translate("MainWindow", "1d"))
        self.TimeComboBox.setItemText(1, _translate("MainWindow", "4h"))
        self.TimeComboBox.setItemText(2, _translate("MainWindow", "1h"))
        self.TimeComboBox.setItemText(3, _translate("MainWindow", "30m"))
        self.TimeComboBox.setItemText(4, _translate("MainWindow", "15m"))
        self.TimeComboBox.setItemText(5, _translate("MainWindow", "5m"))
        self.Label_5.setText(_translate("MainWindow", "볼린져 밴드 설정 :"))
        self.Label_6.setText(_translate("MainWindow", "서칭 기준 :"))
        self.TradeButton_2.setText(_translate("MainWindow", "필터링"))
        self.StatusLabel.setText(_translate("MainWindow", "미조회중"))
        self.PositionButton.setText(_translate("MainWindow", "잔고조회"))
        self.label_2.setText(_translate("MainWindow", "Free :"))
        self.label_3.setText(_translate("MainWindow", "Used :"))
        self.label_4.setText(_translate("MainWindow", "Total :"))
        self.TotalLabel.setText(_translate("MainWindow", "0.0"))
        self.FreeLabel.setText(_translate("MainWindow", "0.0"))
        self.UsedLabel.setText(_translate("MainWindow", "0.0"))
        self.label_7.setText(_translate("MainWindow", "USDT"))
        self.label_8.setText(_translate("MainWindow", "USDT"))
        self.label_9.setText(_translate("MainWindow", "USDT"))
        self.Label_7.setText(_translate("MainWindow", "거래량증가율 :"))
        self.TradeButton_3.setText(_translate("MainWindow", "R"))
        self.StatusLabel_2.setText(_translate("MainWindow", "대기중"))
        self.BalanceGroupBox.setTitle(_translate("MainWindow", "선물 지갑 잔고 현황"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

